elasticsearch/docker/docker-compose.yml, elasticsearch/docker/tests/test_labels.py, elasticsearch/linux_distributions/build.gradle, elasticsearch/version.json, kibana/docker/Makefile, kibana/docker/docker-compose.yml, kibana/docker/templates/Dockerfile.j2, kibana/docker/tests/test_labels.py, kibana/linux_distributions/generate-pkg.sh, kibana/version.json
=> opendistro-for-elasticsearch-1.2.0 Release

kibana/docker/Makefile, kibana/linux_distributions/generate-pkg.sh
=> include kibana-alerting plugin in builds

elasticsearch/linux_distributions/opendistro-tar-build.sh, kibana/linux_distributions/generate-pkg.sh
=> changes for script

elasticsearch/linux_distributions/opendistro-tar-build.sh
=> validation in script

elasticsearch/docker/docker-compose.yml, elasticsearch/version.json, kibana/version.json
Changed version.json in elasticsearch and kibana docker repository to build ES-7.2.1 version.
=> opendistro-1.2.1 release

elasticsearch/linux_distributions/build.gradle
updated version for ES to 7.2.1 in gradle build
=> updated version for ES to 7.2.1 in gradle build

elasticsearch/docker/Makefile, elasticsearch/linux_distributions/build.gradle, elasticsearch/linux_distributions/opendistro-tar-build.sh, elasticsearch/version.json, kibana/docker/Makefile, kibana/linux_distributions/generate-pkg.sh, kibana/version.json
Version upgrade to ES-7.3.2 and ODFE-1.3.0
Added opendistro index management plugin for ES and Kibana
=> Opendistro 1.3 Release Changes

.github/workflows/build-docker.yml, .github/workflows/duild-rpm-deb-tar.yml, elasticsearch/docker/Makefile, elasticsearch/linux_distributions/opendistro-tar-build.sh, kibana/docker/Makefile, kibana/linux_distributions/generate-pkg.sh
-Version bump for ES Alerting, ISM and ISM Kibana plugins from 1.3.0.0 to 1.3.0.1.
=> Updated build scripts for Alerting and ISM plugin bug fixes

helm/CONTRIBUTORS.md, helm/README.md, helm/opendistro-es/.helmignore, helm/opendistro-es/Chart.yaml, helm/opendistro-es/templates/_helpers.tpl, helm/opendistro-es/templates/elasticsearch/elasticsearch-serviceaccount.yaml, helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml, helm/opendistro-es/templates/elasticsearch/es-client-ingress.yaml, helm/opendistro-es/templates/elasticsearch/es-client-pdb.yaml, helm/opendistro-es/templates/elasticsearch/es-config-secret.yaml, helm/opendistro-es/templates/elasticsearch/es-data-pdb.yaml, helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml, helm/opendistro-es/templates/elasticsearch/es-data-svc.yaml, helm/opendistro-es/templates/elasticsearch/es-master-pdb.yaml, helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml, helm/opendistro-es/templates/elasticsearch/es-service.yaml, helm/opendistro-es/templates/elasticsearch/master-svc.yaml, helm/opendistro-es/templates/elasticsearch/role.yaml, helm/opendistro-es/templates/elasticsearch/rolebinding.yaml, helm/opendistro-es/templates/kibana/kibana-config-secret.yaml, helm/opendistro-es/templates/kibana/kibana-deployment.yaml, helm/opendistro-es/templates/kibana/kibana-ingress.yml, helm/opendistro-es/templates/kibana/kibana-service.yaml, helm/opendistro-es/templates/kibana/kibana-serviceaccount.yaml, helm/opendistro-es/templates/kibana/role.yaml, helm/opendistro-es/templates/kibana/rolebinding.yaml, helm/opendistro-es/templates/psp.yml, helm/opendistro-es/values.yaml
=> copied helm folder and updated version to 1.3.0

.github/workflows/build-docker.yml, .github/workflows/check_plugin.yml
=> Opendistro 1.4 minor big fixes

.github/workflows/build-windows.yml, elasticsearch/docker/docker-compose.yml, elasticsearch/linux_distributions/opendistro-windows-build.sh, kibana/linux_distributions/opendistro-windows-kibana-build.sh
Added Windows build workflow with jobs of building artefacts(.exe and .zip) from tarball distribution and releasing it in S3 after testing. For testing the artefacts, integTest of Alerting and ISM plugins are leveraged.
=> Rish1397 windows automation

elasticsearch/linux_distributions/opendistro-tar-build.sh, elasticsearch/linux_distributions/opendistro-tar-install.sh
The tar build now installs the kNN plugin in the artefact. Also updated the tar installation script which now fetches the kNN lib froms3 and put it in place.
=> Srivasri adding knn tar

release-notes/release-notes-odfe-1.6.0.md
removing mentions of sql kibana UI
=> removed SQL kibana UI

release-notes/release-notes-odfe-1.6.0.md
Reverts opendistro-for-elasticsearch/opendistro-build#109
=> Revert "removed SQL kibana UI"

.github/workflows/build-deb.yml, .github/workflows/build-rpm.yml, .github/workflows/build-tar.yml, .github/workflows/check_plugin.yml, download_kibana_plugins.sh, download_plugins.sh, elasticsearch/docker/Makefile, elasticsearch/linux_distributions/build.gradle, elasticsearch/linux_distributions/opendistro-tar-build.sh, elasticsearch/linux_distributions/opendistro-windows-build.sh, kibana/docker/Makefile, kibana/linux_distributions/generate-pkg.sh
Support new plugins: Anomaly Detection and SQL Kibana
=> Support new plugins: Anomaly Detection and SQL Kibana

elasticsearch/linux_distributions/build.gradle, elasticsearch/version.json, kibana/version.json
=> OD Version upgrade to 1.7.0

.github/workflows/build-deb.yml, .github/workflows/build-rpm.yml, .github/workflows/build-tar.yml, .github/workflows/check_plugin.yml
Adding repository dispatch event for all schedules workflows for manual trigger if needed
=> Adding repository dispatch event for manual trigger

.github/workflows/build-deb.yml, .github/workflows/build-rpm.yml, .github/workflows/build-tar.yml, .github/workflows/check_plugin.yml, .github/workflows/webhook-build-docker.yml
=> Number of plugins changed

elasticsearch/linux_distributions/build.gradle
Update the AD plugin name for Deb and RPM
=> Update the AD plugin name for Deb and RPM

.github/workflows/webhook-build-docker.yml
add event type for docker workflow
=> add event type for docker workflow

.github/workflows/webhook-build-docker.yml
The lambda function can't work to trigger the docker image. use daily schedule as temporary solution
=> Add Daily Schedule temporarily for 1.7.0 Release

.github/workflows/build-windows.yml
Support manual event for windows build workflow
=> Support manual event for windows build workflow

.github/workflows/build-windows.yml
not familiar with testing in Python, please raise an issue instead.
=> action version change reverted

.github/workflows/build-AMI.yml, .gitignore, elasticsearch/AMI/lib/ODFEInstaller.py, elasticsearch/AMI/lib/instance.py, elasticsearch/AMI/main.py, elasticsearch/AMI/requirements.txt, elasticsearch/AMI/tests/test_instance.py, elasticsearch/AMI/tests/test_odfenstaller.py
Created Open distro AMI creation script and workflow file.
=> Added AMI build script and workflow file

elasticsearch/docker/Makefile, elasticsearch/docker/templates/Dockerfile.j2
AD plugin has dependency on Job Scheduler
=> use manual way to control the plugin orders for docker image creation

.github/workflows/sync-deb-prod.yml
=> Add deb prod release workflow

.github/workflows/check_plugin.yml, elasticsearch/linux_distributions/build.gradle, elasticsearch/version.json, kibana/version.json
ES version bump to 7.7.0 and OD version to 1.8.0. Disable scheduled workflow for daily plugin check
=> ES version bump to 7.7.0 and OD version to 1.8.0

.github/workflows/check_plugin.yml, .github/workflows/check_plugin_temp.yml
This PR is trying to allow user override to the env variables that controls the behavior of the workflow in check_plugin.yml.
=> Try to allow user to disable alerts

elasticsearch/linux_distributions/build.gradle
=> update the AD plugin artifact name for deb and rpm package

elasticsearch/linux_distributions/build.gradle
=> fix the AD plugin name

.github/workflows/test-build-tar.yml
=> Java version updated to 14

.github/workflows/test-build-tar.yml
=> cluster name added

.github/workflows/test-build-deb.yml
=> Update jdk version and fix IT error for deb workflow

.github/workflows/test-webhook-build-docker.yml
=> Add clustername for IT and use jdk 14

.github/workflows/check_plugin.yml, .github/workflows/check_plugin_temp.yml, .github/workflows/test-build-deb.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml, .github/workflows/test-build-windows.yml, .github/workflows/test-webhook-build-docker.yml, download_kibana_plugins.sh, kibana/linux_distributions/generate-pkg.sh
This PR is to complete the user control integration to alert messages on Chime and Emails.
In preparation for this PR here: #165 
It also update the kibana sql plugin to new naming convention:
-opendistro-sql-kibana/sql-kibana"
+opendistro-sql-workbench/opendistro-sql-workbench
=> Tweak check_plugin_temp.yml and update kibana sql plugin names

.github/workflows/check_plugin.yml, .github/workflows/check_plugin_temp.yml
This PR is to eventually fix the long-standing user overrides on alert sendings.
This also disable the schedule event for check_plugin.yml.
=> Tweak if condition for alert triggerings 

.github/workflows/test-build-rpm.yml
Adds IT for RPM artifacts
Self hosted runner is set up and is actively working. 
I have [tested](https://github.com/gaiksaya/opendistro-build/actions/runs/112947452) in my repo.
=> Adds IT for RPM artifacts

.github/workflows/test-build-rpm.yml
Git preinstalled now within the ebs volume, Snapshot Id changed to recent one and label changed to odfe-rpm
=> Git preinstalled, label renamed and Snapshot id changed

.github/workflows/test-build-deb.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml
This PR is to resolve the longtime typo get triggered in #184.
=> Resolve the typo in step names

.github/workflows/test-webhook-build-docker.yml
=> Changing the repository reference to tags(v1.8.0.0)

elasticsearch/docker/templates/Dockerfile.j2
=> update the branch for knn

.github/workflows/test-build-deb.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml
This PR is to update the parameter names that contains typos to the build workflows.
https://github.com/lewagon/wait-on-check-action#example-workflow-code
=> Update parameter names for certain actions

.github/workflows/test-build-deb.yml, .github/workflows/test-build-tar.yml, .github/workflows/test-build-windows.yml
Used outputs as it will be easy to replace/modify just one code block in future
=> Replacing git reference from master to version tags

.github/scripts/check_plugin.sh, .github/workflows/check_plugin.yml, .github/workflows/check_plugin_old.yml, .github/workflows/test-build-deb.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml
This PR is to port the check_plugin.yml workflow to a script for lightweight access by other workflows.
1. Success case: 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/119475111
2. Failure case:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/119473418
=> Port check_plugin workflow to lightweight script

.github/workflows/release-sync-deb.yml, .github/workflows/release-sync-rpm.yml, .github/workflows/release-sync-tar.yml, .github/workflows/release-sync-windows.yml, .github/workflows/test-build-ami.yml, .github/workflows/test-build-deb.yml, .github/workflows/test-build-docker.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml, .github/workflows/test-webhook-build-docker.yml
This PR is to improve the naming conventions, trigger events, and more for workflow consistencies here.
=> Improve naming conventions

.github/scripts/check_plugin.sh
This PR is to fix a small error related to the check_plugin.sh scripts.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/121729325
=> Improve root directory assignment for the scripts

.github/scripts/check_plugin.sh, .github/workflows/test-build-deb.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml
This PR is to further improve the utilization of the check_plugin.sh scripts for tar/deb/rpm workflows.
=> Tweak the scripts to utilize parameters

.github/workflows/release-sync-tar.yml, .github/workflows/release-sync-windows.yml
This PR is to tweak release workflow for tar and windows, fix the issues with the s3 cp actions.
=> Tweak release workflow for tar and windows

.github/workflows/release-sync-ami.yml
This PR is to make a workflow for ami in release-sync-ami.yml so that ami can be set to public in all regions automatically.
=> Workflow to make AMI public in all regions

.github/workflows/release-sync-ami.yml
This PR is to tweak AMI workflow to change regions.
Workflow: https://github.com/peterzhuamazon/opendistro-build/actions/runs/122965561
=> Tweak AMI workflow to change regions

helm/opendistro-es/Chart.yaml, helm/opendistro-es/values.yaml
=> Helm version upgrade

.github/workflows/test-build-deb.yml
692 tests completed, 1 failed, 42 skipped
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/737098855?check_suite_focus=true
=> Add SQL IT against security enabled cluster

.github/workflows/test-build-deb.yml
Added modifications that are required for ISM IT (Snapshot Test). 
Also removed jdk11 installation in the process as we are already installing jdk14. (Need to do this for all other tests too in this yml. Will raise a new PR for that later)
[Test](https://github.com/gaiksaya/opendistro-build/runs/740030967?check_suite_focus=true)
=> Modifications for ISM IT

.github/workflows/test-build-rpm.yml
Modifications for ISM IT for RPM distributions
[Test](https://github.com/gaiksaya/opendistro-build/actions/runs/125293291/)
=> Modifications for ISM IT (RPM)

release-notes/opendistro-for-elasticsearch-release-notes-1.0.0.md, release-notes/opendistro-for-elasticsearch-release-notes-1.8.0.md
This PR is to update release notes related to build issue 51 on breaking changes.
https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/51
=> Updating release notes related to build issue 51 on breaking changes

release-notes/opendistro-for-elasticsearch-release-notes-1.0.0.md, release-notes/opendistro-for-elasticsearch-release-notes-1.8.0.md
This PR is to update opendistro-1.8 branch with 1.0.0/1.8.0 breaking changes support docs
=> Update opendistro-1.8 branch with 1.0.0/1.8.0 breaking changes support docs

elasticsearch/linux_distributions/build.gradle
=> Remove KNN lib preinstall script

bin/version.json, elasticsearch/linux_distributions/build.gradle
This PR is to make changes in preparation for 1.8.1 releases.
=> Make version changes for 1.8.1 releases

elasticsearch/docker/templates/Dockerfile.j2
The way of knn lib  building need be updated to the new one. This PR is to make this change
Tested with 1.8.0 ODFE version. 1.8.1 version need be tested in the latest new release
=> Update the knn lib for docker image 

.github/scripts/check_plugin.sh, .github/scripts/plugin_tag.sh, .github/workflows/check_plugin.yml, .github/workflows/test-build-deb.yml
This PR is a follow up to #209 to also allow integTest to consume the latest plugin versions of the current release.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/137857126
=> Plugin Version Optimization Part2 deb integTest Workflows

.github/scripts/check_plugin.sh
This PR is to improve the check_plugin scripts and correct a bug that was introduced in #268.
=> Improve check_plugin scripts

.github/scripts/plugin_tag.sh, .github/workflows/test-build-deb.yml, .github/workflows/test-build-docker.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml, .github/workflows/test-build-windows.yml
This PR is a follow up to #209 #268, and include majority of the distributions IntegTest workflows with plugin version optimizations changes.
- docker: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/138822969
- tar: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/138822973
- deb: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/138841345
- rpm: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/138822970
- windows: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/140156429
=> Plugin Version Optimization Part2 Major IntegTest Workflows

.github/workflows/check_plugin.yml, bin/version.json, elasticsearch/linux_distributions/build.gradle
This PR is to make version changes to ODFE 1.9.0 releases.
=> Make version changes to ODFE 1.9.0 releases

elasticsearch/linux_distributions/opendistro-tar-install.sh
This PR is a follow up to #272 and add macOS support for new KNN lib loading methods.
=> Add macOS support for new KNN lib loading methods

elasticsearch/linux_distributions/opendistro-tar-build.sh
use the new knn lib .so file for new release.  This is short term solution. @jmazanec15 will have a followup for long term plan
=> use new knn lib .so file for tarball release

bin/plugins.json
=> Change the plugin orders

.github/workflows/test-build-tar.yml
This PR is to add unzip installation to the tar workflows.
=> Adding unzip installation

kibana/docker/templates/Dockerfile.j2, kibana/linux_distributions/opendistro-kibana-build.sh
Reverts opendistro-for-elasticsearch/opendistro-build#287
=> Remove the temp solution

elasticsearch/linux_distributions/opendistro-tar-build.sh, elasticsearch/linux_distributions/opendistro-tar-install.sh
Does this PR include tests? No, these are bash build changes for performance_analyzer
=> Modify tarball scripts to work with RCA

.github/workflows/check-version-upgrade.yml
This PR includes addition of extra commands to handle broken packages for DEB and RPM
Also modified the aws commands to reset the host runner inorder to avoid conflict with already existing EBS volumes
Tested- https://github.com/gaiksaya/opendistro-build/runs/824717909?check_suite_focus=true
=> Adding additional commands to upgrade from staging

.github/workflows/test-build-deb.yml, .github/workflows/test-build-docker.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml, .github/workflows/test-build-windows.yml, .github/workflows/test-cluster-static-domain-set-up.yml
This PR is to add previous versions and also disable schedule runs in the workflows.
=> ODFE 1.9.0 release disable build workflows 

.github/workflows/test-cluster-delete.yml
Secrets name rectified for AWS creds
=> secrets name rectified

bin/plugins.json, elasticsearch/windows/opendistro-windows-build.sh
This PR is to Remove KNN and PA from the windows distros as they are not currently supported in windows.
=> Remove KNN and PA from the windows distros

release-notes/opendistro-for-elasticsearch-release-notes-1.9.0.md
This PR is to add the ODFE 1.9.0 distribution release notes to the master repo here.
=> Add ODFE 1.9.0 distribution release notes

helm/opendistro-es/Chart.yaml, helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml, helm/opendistro-es/templates/elasticsearch/es-data-svc.yaml, helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml, helm/opendistro-es/templates/elasticsearch/es-service.yaml, helm/opendistro-es/values.yaml
This PR is to bump the HELM version to 1.9.0.
=> Make HELM version bump to 1.9.0

.github/workflows/test-build-ami.yml
This PR is to make additional removal for ami to work in building processes.
=> Additional removal for ami to work in building processes

bin/version-info, bin/version.json
This PR is to add previous versions for version-info checks.
=> HOLDING: Add previous versions for version-info checks

.github/scripts/check_plugin.sh
This PR is to add color coding with in-progress artifact status for check_plugin workflows.
It also updates the email and chime messages.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/154458492
=> Add color coding with in-progress artifact status for check_plugin workflows

.github/scripts/check_plugin.sh, bin/plugins.json
This PR is to add cli dvr plugin checks in workflows, such as sql cli, jdbc, odbc, perfTop.
This is also a follow up PR to #298.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/159848789
=> HOLDING: Add cli dvr plugin checks in workflows

.github/scripts/plugin_tag.sh, elasticsearch/docker/templates/Dockerfile.j2
This PR is to make patch version optimization with 2 digits checks, not using 3 digits anymore to follow up with the version optimization in ODFE.
=> Make patch version optimization with 2 digits checks

.github/workflows/test-build-deb.yml, .github/workflows/test-build-docker.yml, .github/workflows/test-build-rpm.yml, .github/workflows/test-build-tar.yml
This PR is to replace personal READ_TOKEN with bot private token.
We have already sent a ticket [HERE](https://t.corp.amazon.com/V228985384) to add bot to the private repos.
=> Replace personal READ_TOKEN with bot private token

helm/opendistro-es/templates/kibana/kibana-ingress.yml, helm/opendistro-es/values.yaml
Hi,
this is for fixing #307
I did
- user can input multiple hosts -> user can input only one host
- fix ingress path
- etc
=> helm - kibana ingress path fix

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/query.md, .github/PULL_REQUEST_TEMPLATE.md
Adding Issue Template:
- Bug
- Query
- Feature request
Adding PR template
=> Update issue templates

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/346
*Description of changes:* Hook alerting IT with security to all distributions
- DEB: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/995559159?check_suite_focus=true
- RPM: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/212802592
- TAR: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/996047260?check_suite_focus=true
- DOCKER: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/996085569?check_suite_focus=true
- WINDOWS: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/996150073?check_suite_focus=true
By submitting this pull request, I confirm that my …
=> Add IT with security for alerting

.github/scripts/check_plugin.sh, .github/workflows/check-plugin.yml, bin/version.json
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/249
This PR is to enable slack alerts for ODFE 1.10.0 Version.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/215713678
=> Enable Slack Alerts in ODFE 1.10.0

.github/workflows/staging-build-rpm.yml
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/251
Fix the typo error in CleanUp-Runners job
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1058359028?check_suite_focus=true
=> Fix the typo error in CleanUp-Runners job

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/test-cluster-static-domain-set-up.yml
Activate scheduling for all build workflows and testing domains
No need to test as they are already tested, just activating the schedule
=> Activate scheduling for all build workflows and testing domains

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/test-cluster-static-domain-set-up.yml
Disable automatic build schedule till next release artifacts are ready
Not required
=> Disable automatic build schedule

README.md
Update issue hyperlink to this repo's issues
Not required
=> Update issues link in readme file

.github/scripts/userdata.sh, .github/templates/odfe-testing-cluster-static-domain-template.json, .github/workflows/test-cluster-static-domain-set-up.yml
https://github.com/opendistro-for-elasticsearch/opendistro-infra/projects/8
1. Add endpoint for PA on port 9600
2. Create new LB with port 9600 manually and map it to the appropriate target group
3. Modify the ES/Kibana installation (userdata script) to expose the PA accessible outside the cluster
4. Change AMI with recent ones
5. Refactor userdata.sh
6. Refactor set-up workflow to remove tmp files
All the testing domains are active. Verified working of all.
=> Testing domain PA fix and refactor

.github/workflows/check-version-upgrade.yml
**Issue #, if available:**
**Description of changes:**
Add ES curl statements for verification and version check. 
**Test Results:**
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/279255093
=> Add curl statements for verification and version check

release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/255
This PR is to update opendistro-for-elasticsearch-release-notes-1.10.1.md and remove Notes Section
No need as it is just a documentation update
=> Update opendistro-for-elasticsearch-release-notes-1.10.1.md and remove Notes Section

release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/255
This PR is to update opendistro-for-elasticsearch-release-notes-1.10.1.md for more syntax fixes
No Need
=> Update opendistro-for-elasticsearch-release-notes-1.10.1.md for more syntax fixes

release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
Many grammar fixes (correct tense, capitalization, etc).
Documentation change.
=> Grammar fixes for 1.10.1 release notes

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values.yaml
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/254
This PR is to update helm chart with the latest ODFE 1.10.1 versions
It is just a version bump, will test manually on ELK once it is merged.
=> Update helm chart with the latest ODFE 1.10.1 versions

release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
https://github.com/opendistro/for-elasticsearch/pull/88
This PR is to add new changes based on [#88](https://github.com/opendistro/for-elasticsearch/pull/88) for-elasticsearch PR by Viraj
No need as it is a documentation change
=> Add new changes based on #88 for-elasticsearch PR by Viraj

.github/scripts/setup_runners.sh
P40579132
This PR is to add refactoring of setup runner scripts with comments addition and variable name changes
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/295742561
=> Refactoring of setup runner scripts with comments addition and variable name changes

bin/version.json
Update version numbers for ODFE 1.11.0
=> Update version.json for ODFE 1.11.0 release

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/test-cluster-static-domain-set-up.yml
=> Enable cron jobs for staging workflows and test domain setup

.github/workflows/check-vulnerability-whitesource.yml, .github/workflows/wss-scan.yml, standalone-tools/wss-scan.config, standalone-tools/wss-scan.sh, standalone-tools/wss-unified-agent.config
Add standalone-tools for the WhiteSource scan of the ODFE repositories. The workflow will be scheduledto run the job daily at 3:30AM. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/311674184
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/316478846
=> Adding WhiteSource Scan for repos within opendistro-for-elasticsearch org on GitHub

standalone-tools/wss-scan.sh
…omplete
Change wait process to capture and wait for all child processes to complete
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/316478846
=> Modify the scan script to capture child PID's and wait till completed

bin/plugins.json
The alerting team has new versions of their plugins for ODFE 1.11.0
=> Update alerting and alerting-kibana to 1.11.0.1 and 1.11.0.2 respectively

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/test-cluster-static-domain-set-up.yml
Disable scheduled builds and test clusters
=> Disable scheduled staging builds and test cluster setup

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values.yaml
P41163474
This PR is to Update Helm version from 1.10.1 to 1.11.0 for ODFE.
No Need
=> Update Helm version from 1.10.1 to 1.11.0 for ODFE

release-notes/opendistro-for-elasticsearch-release-notes-1.11.0.md
=> Add ODFE 1.11.0 release notes

.github/workflows/check-vulnerability-whitesource.yml, standalone-tools/wss-scan.sh, standalone-tools/wss-unified-agent.config
Remove the parallel processing and make the vulnerability scan sequential. This is due to the wait command is working inconsistently. Also add an additional scan configuration for the Maven repos. 
Full scan test : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/342127212
=> Remove the parallel processing and make the vulnerability scan sequential

.github/workflows/prod-sync-ami.yml
1. Add cli_pager="" option to eliminate the interactive shell that returns null for our workflows [Details](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager)
2. Clean up the workflow by removing unused commands
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1376369233?check_suite_focus=true
=> Fix prod-sync-ami.yml workflow

bin/version.json
Change version.json for the ODFE new release 1.12.0
Not needed
=> Change version.json for the ODFE new release 1.12.0

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml
P41822381
Removing java 15 from matrix to avoid noise during release cycle. 
Not required.
=> Remove java 15 from the matrix

.github/workflows/check-plugin.yml
Reformat yml
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/375357246
=> Reformat yml

helm/opendistro-es/values.yaml
There are a couple of typos in the helm charts `values.yaml` file.
=> fix(helm): Fixes a typo in helm values.yaml

.github/workflows/check-plugin.yml
Disable check plugin as we have all plugin available now
Not required
=> Disable check plugin

.github/workflows/staging-build-docker.yml
V286570428
This PR is to make the pip installation globally visible
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/399566033
=> Make the pip installation globally visible

.github/workflows/codeql-analysis.yml
Remove scheduled run of codeql
No test needed
=> Remove scheduled run of codeql

.github/scripts/setup_runners_service_windows.ps1
Change security kibana plugin name in windows installation script
=> Change security kibana plugin name in windows installation script

.github/workflows/staging-build-windows.yml
P42246929
Fix windows test for AD plugin. Arguments were missing spaces due to which it was failing. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1500896434?check_suite_focus=true
=> Fix windows IT test for AD plugin

.github/workflows/prod-sync-data-prepper.yml, .github/workflows/staging-build-data-prepper.yml, bin/plugins.json
V279188473
This PR is to add Data Prepper related workflows to master branches 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/407172716
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/407177381
=> Add Data Prepper related workflows to master branches 

bin/plugins.json
P42353663
Remove trace analytics plugins from this release (ODFE 1.12.0)
Not required
=> Remove trace analytics plugin from ODFE 1.12.0

.github/workflows/staging-build-data-prepper.yml, .github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker-ci.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml
V288944977
This PR is to add docker logout and tag to latest before push
No need.
=> Add docker logout and tag to latest before push

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml
P42383284
Got a request from alerting team to add `-Dsecurity=true` for alerting with security IT tests.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/411232484
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/411232483
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/411232482
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/411250847
=> Fix alerting IT for with security by adding a gradle param in the command

bin/plugins.json, bin/version.json
Cut version for ODFE 1.12.0 release
Not required
=> Cut version for ODFE 1.12.0 release

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/test-cluster-static-domain-set-up.yml
P42448487
disable schedule as phase 3 ends
N/A
=> Disable schedule

.github/workflows/staging-build-docker.yml
Disable email for docker workflow
N/A
=> Disable mail

.github/workflows/staging-build-ami.yml
V290419891
This PR is to add new security group for ami creation.
Will test once it is merged to master
=> Adding new security group for ami creation

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values.yaml
Update Helm version from 1.11.0 to 1.12.0 for ODFE 1.12.0 release
Test will be done locally 
=> Update Helm version from 1.11.0 to 1.12.0 for ODFE 1.12.0 release

.github/workflows/staging-build-ami.yml
v290419891
This PR is to create new SG for the AMI
Will test with the master branch
=> Create new SG for the AMI

standalone-tools/wss-scan.config
Add kibana reports to WhiteSource daily scan
=> Add kibana reports to WhiteSource daily scan

.github/workflows/test-cluster-set-up.yml, .github/workflows/test-cluster-static-domain-set-up.yml, release-tools/scripts/manifest.yml, release-tools/scripts/userdata.sh
P42830036
1. Make changes to grab scripts from new folder structure
2. Change the account for configuring these cluster to our own (infra) testing account
3. Also configured all the load balancers, users, roles, etc in testing account that will be used in creation and mapping of these clusters
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1603283805?check_suite_focus=true
=> Test cluster fixes with respect to new folder structure

.github/workflows/check-plugin.yml, release-tools/scripts/check_plugin.sh, release-tools/scripts/manifest.yml, release-tools/scripts/plugin_tag.sh, release-tools/scripts/plugins-info.sh, release-tools/scripts/required_packages.sh
P40553676
This PR is to rewrite manifest yaml and update check-plugin workflows 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/449429981
=> Rewrite manifest yaml and update check-plugin workflows 

.github/workflows/check-vulnerability-whitesource.yml, standalone-tools/wss-scan.config
Update WhiteSource workflow as per the new ODFE structure and add new plugin repos to the daily scan. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/449229412
=> Update WhiteSource workflow as per the new ODFE structure and add new plugin repos to the daily scan. 

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .gitignore, release-tools/scripts/setup_runners_service.sh, release-tools/scripts/setup_runners_service_windows.ps1, release-tools/scripts/version-info.py
P42915102, https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/522
- Add integration test for security kibana plugin.
- Make changes to installation scripts to add the setting as per conversation with security kibana team
- The test have been added with new folder structure in mind. No changes have been made to other tests
- Change version.py env to python instead of python3 as windows github actions is giving issues
- Windows: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/452139633
- RPM: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/451870374
- DEB: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/451798083
- …
=> Add integration test for security kibana plugin 

.github/workflows/check-vulnerability-standalone.yml
Workflow to run individual WhiteSource scan for the GIT Repo. This workflow takes Branch name and GIT repo name as parameters. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/461369673
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/461955007
=> Workflow to run individual WhiteSource scan for the GIT Repo

release-tools/scripts/manifest.yml
Add default key for staging S3 locations and add ODFE CLI
No test needed
=> Add default key for staging S3 locations and add ODFE CLI in manifest.yml

release-tools/scripts/manifest.yml
Add release candidate field in manifest.
Not needed. 
=> Add release candidate field in manifest

release-tools/scripts/manifest.yml
P43270397
Add reports scheduler in manifest.yml and set trace-analytics to RC-false
Not required
=> Add reports-scheduler in manifest.yml

.github/workflows/prod-sync-odfe-cli.yml, .github/workflows/staging-odfe-cli.yml, release-tools/scripts/manifest_parser.sh, release-tools/scripts/plugin_parser.sh, release-tools/scripts/required_packages.sh
Add staging and Prod-sync workflow for ODFE CLI and add manifest parser script. Also change the yq version from 4.0.0 to 4.2.1.
Staging: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/464440637
Prod-sync:https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/464499750
=> Add Staging and Prod-sync workflow for ODFE CLI and add manifest parser script 

release-tools/scripts/setup_runners.sh
V301153385
This PR is to increase delay more and add an option to specify other repos for bootstrapping runners
https://github.com/opendistro-for-elasticsearch/k-NN/actions/runs/473100150
=> Increase delay more and add an option to specify other repos for bootstrapping runners

standalone-tools/wss-scan.config
Add asynchronous-search to the WhiteSource daily scan
No test needed
=> Add asynchronous-search to the WhiteSource daily scan

.github/workflows/prod-sync-odfe-cli.yml, .github/workflows/staging-odfe-cli.yml
Disable the schedule for staging and also change the filter as per the new naming of the odfe cli
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/502207910
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/502190719
=> Disable the schedule for staging and also change the filter as per the new naming of the odfe cli

.github/workflows/staging-build-docker.yml
V306623151
Add required packages for each job
Reformat the code
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/502156511
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1745168947?check_suite_focus=true
=> Reformat docker staging and test IT

release-tools/scripts/manifest.yml
change the ES and kibana version for the download url
No test required. 
=> change the ES and kibana version for the download url

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml
P43691486
It was informed to me that kibana-notebooks is going to maintain its folder structure as per `1.12.0`. Hence making changes to keep the same
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/504496899
=> Update kibana notebooks path

.github/workflows/staging-build-windows.yml, release-tools/scripts/setup_runners_service_windows.ps1
V306623315
Fix windows installation script to use new staging location and add arch as well as new product name
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1752007017?check_suite_focus=true
SQL failed due to flaky test and kibana-notebooks do not have windows fix in `v1.12.0.0` tag
=> Update windows installation script and test IT

release-tools/scripts/manifest.yml
P40553676
This PR is to add arm64 zip for knnlib in ES
No Need
=> Add arm64 zip for knnlib in ES

release-tools/scripts/manifest.yml
P40553676
This PR is to correct the arm64 knnlib syntax in manifest.yml 
No Need
=> Correct the arm64 knnlib syntax in manifest.yml 

.github/workflows/staging-build-tar-arm64.yml, .github/workflows/staging-build-tar.yml, elasticsearch/linux_distributions/opendistro-tar-build.sh, kibana/linux_distributions/opendistro-kibana-build.sh, release-tools/scripts/manifest.yml, release-tools/scripts/required_packages.sh, release-tools/scripts/setup_runners.sh
P40553676
This PR is to add arm64 tar building for both ES and KIBANA
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/513170054
=> Add arm64 tar building for both ES and KIBANA

.github/workflows/staging-build-rpm.yml
change rpm workflow for the ES and Kibana IT as per the new ODFE structure
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/513716555
=> change rpm workflow for the ES and Kibana IT as per the new ODFE structure

release-tools/scripts/manifest.yml
V309387707
This PR is to add async search es plugin to ODFE building process
Locally tested to convert the yaml to json.
=> Add async search es plugin to ODFE building process

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar-arm64.yml, .github/workflows/staging-build-tar.yml, elasticsearch/linux_distributions/build.gradle, release-tools/scripts/manifest.yml, release-tools/scripts/setup_runners_service.sh
V306623281
This PR is to make deb integTest runs work with new env
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/522242751
=> Make deb integTest runs work with new env

.github/workflows/check-plugin.yml, .github/workflows/staging-copy-artifacts.yml, release-tools/scripts/manifest.yml
schedule check plugin workflow and change manifest as per the new release
=> ODFE 1.13.0: Schedule check plugin workflow and change manifest versions

.github/workflows/staging-build-docker.yml, .github/workflows/staging-build-tar-arm64.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/staging-test-deb-arm64.yml, .github/workflows/staging-test-deb-x64.yml, .github/workflows/staging-test-rpm-arm64.yml, .github/workflows/staging-test-rpm-x64.yml, .github/workflows/staging-test-tar-arm64.yml, release-tools/scripts/setup_runners.sh
* Adds support for security enabled Index Management integration tests as they are now supported [#379](https://github.com/opendistro-for-elasticsearch/index-management/pull/379)
* Renames ISM -> IM in repository
=> Adds support for Index Management security tests and renames ISM -> IM

.github/workflows/staging-build-tar.yml, release-tools/scripts/setup_runners_service.sh
Fix setup runner service script to use remove overwriting of the Architecture
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/548845133
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/549114661
=> Fix setup runner service script to use remove overwriting of the Architecture

.github/workflows/test-cluster-static-domain-set-up.yml, release-tools/scripts/userdata.sh, release-tools/templates/odfe-testing-cluster-static-domain-template.json
V312676618
Refactor the code and add ARM64 testing cluster config
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/542192034
=> Add testing clusters for ARM64

.github/workflows/staging-build-windows.yml, kibana/windows/opendistro-windows-kibana-build.sh, release-tools/scripts/setup_runners_service_windows.ps1
Change the IT dependency in windows workflow and make changes in Kibana build script
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/549501529
=> Change the IT dependency in windows workflow and make changes in Kibana build script

.github/workflows/staging-test-deb-arm64.yml, .github/workflows/staging-test-rpm-arm64.yml, .github/workflows/staging-test-rpm-x64.yml, .github/workflows/staging-test-tar-arm64.yml, .github/workflows/staging-test-tar-x64.yml, release-tools/scripts/setup_runners_service.sh
V313270097
This PR is to make correction to tar deb rpm workflows
No Need.
=> Correction to tar deb rpm workflows

.github/workflows/test-cluster-static-domain-set-up.yml, release-tools/scripts/setup_runners_service.sh, release-tools/scripts/setup_runners_service_windows.ps1, release-tools/scripts/userdata.sh
P44203720
- Change PA name to make config changes
- Change `opendistro-security` plugin name in installation scripts
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/549900096
```
curl -XGET http://$es:9600/_opendistro/_performanceanalyzer/rca -u admin:admin --insecure
{"QueueRejectionRca":[{"rca_name":"QueueRejectionRca","timestamp":1612896026256,"state":"healthy"}],"ShardRequestCacheRca":[{"rca_name":"ShardRequestCacheRca","timestamp":1612896026261,"state":"healthy"}],"FieldDataCacheRca":[{"rca_name":"FieldDataCacheRca","timestamp":1612896026260,"state":"healthy"}],"HighCpuRca":[{"rca_name":"HighCpuRca","timestamp":1612896026265,"state":"healthy"}],"HighHeapUsageOldGenRca":[{"rca_name":"HighHe …
```
=> Fix PA in the userdata script and security plugin name in all installation scripts

release-tools/scripts/setup_runners_service.sh, release-tools/scripts/setup_runners_service_windows.ps1, release-tools/scripts/userdata.sh
Revert security plugin name until further notice
=> Revert security plugin name change

.github/PULL_REQUEST_TEMPLATE.md
P44122942
Add DCO guideline to the Pull Request template
=> Add Developer certificate to PR template

.github/workflows/staging-build-docker.yml, .github/workflows/staging-build-windows.yml, .github/workflows/staging-test-deb-arm64.yml, .github/workflows/staging-test-deb-x64.yml, .github/workflows/staging-test-rpm-arm64.yml, .github/workflows/staging-test-rpm-x64.yml, .github/workflows/staging-test-tar-arm64.yml, .github/workflows/staging-test-tar-x64.yml
ISM security integration tests not tested properly before merged in with the amount of test failures reported. As this is not a regression (these integration test workflows never existed before a couple days ago) we are removing this and will work on integrating correctly after to prioritize more important release tasks. The IM security features will be tested manually and signed off on.
have the …
=> Removes ISM security enabled tests

release-tools/templates/odfe-testing-cluster-static-domain-template.json
Fix AMI ids in cloudformation template
Not required
(c) The contribution was provided directly to me by some other
person who certified (a), …
=> Fix AMI ids

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/staging-copy-artifacts.yml, .github/workflows/staging-test-deb-arm64.yml, .github/workflows/staging-test-deb-x64.yml, .github/workflows/staging-test-rpm-arm64.yml, .github/workflows/staging-test-rpm-x64.yml, .github/workflows/staging-test-tar-arm64.yml, .github/workflows/staging-test-tar-x64.yml, .github/workflows/test-cluster-static-domain-set-up.yml
setup schedule run to build and run IT
No test needed.
by me, …
=> setup schedule run to build and run IT

release-tools/scripts/userdata.sh
P44276565
This PR add the required packages to make kibana reports work on testing clusters.
Not required
(c) The contribution was provided …
=> Add dependencies for kibana reports

.github/workflows/staging-test-deb-arm64.yml, .github/workflows/staging-test-rpm-arm64.yml, .github/workflows/staging-test-rpm-x64.yml, .github/workflows/staging-test-tar-arm64.yml, release-tools/scripts/required_packages.sh, release-tools/scripts/setup_runners.sh
P44276565
This PR is to update runners with reports kibana dependencies
No Need.
work with modifications, whether created in …
=> Update runners with reports kibana dependencies

release-tools/scripts/manifest.yml
change the version for IM kibana to 1.13.0.1 in Manifest
Tested manifest in the local. 
work with modifications, whether …
=> change the version for IM kibana to 1.13.0.1 in Manifest

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml
Missed to update AMI ids here https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/626
[Reference code](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/main/release-tools/scripts/setup_runners.sh#L127-L132)
by me, under the same open …
=> Update AMI ids

.github/workflows/staging-build-deb.yml, .github/workflows/staging-build-docker.yml, .github/workflows/staging-build-rpm.yml, .github/workflows/staging-build-tar.yml, .github/workflows/staging-build-windows.yml, .github/workflows/staging-copy-artifacts.yml, .github/workflows/staging-test-deb-arm64.yml, .github/workflows/staging-test-deb-x64.yml, .github/workflows/staging-test-rpm-arm64.yml, .github/workflows/staging-test-rpm-x64.yml, .github/workflows/staging-test-tar-arm64.yml, .github/workflows/staging-test-tar-x64.yml, .github/workflows/test-cluster-static-domain-set-up.yml
Disable scheduled runs for the ODFE build and IT
work with modifications, whether created in whole or in …
=> Disable scheduled runs for the ODFE build and IT

release-tools/scripts/manifest.yml
V316092373
Lock all version numbers and build numbers for final ODFE builds
To-Do:
Add Kibana reports build number
`yq eval '.' release-tools/scripts/manifest.yml` was successful locally.
permitted to submit under a …
=> Add build numbers for final build

.github/workflows/staging-copy-artifacts.yml, release-tools/scripts/staging-copy-artifacts.py
change the build number from int from string in the staging copy script. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/569865525
permitted to submit under a different license), as …
=> change the build number from int from string in the staging copy script. 

.github/workflows/prod-sync-data-prepper.yml
V311401608
This PR is to add required packages and remove the data prepper source S3 bucket
No Need.
work with …
=> Add required packages and remove the data prepper source S3 bucket

.github/workflows/prod-sync-data-prepper.yml
V311401608
This PR is to add more improvement to the data prepper prod sync workflow
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/572875208
license and I …
=> Add more improvement to the data prepper prod sync workflow

release-tools/scripts/manifest.yml
Kibana reports has a bug fix and has been fixed in build-18. Updating the same in manifest file
`yq eval '.' release-tools/scripts/manifest.yml` passes.
in …
=> Bump kibana reports build number

.github/workflows/prod-sync-ami.yml, .github/workflows/prod-sync-artifacts.yml, .github/workflows/staging-build-ami.yml, release-tools/scripts/manifest.yml
Add the release number in the manifest and change the staging ami as per the new ODFE structure.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/575122905 …
=> Add the release number in the manifest and change the staging ami as per the new ODFE structure.

.github/workflows/prod-sync-deb.yml
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1922019615?check_suite_focus=true#step:4:63
Add checkout so that gits checkout our repo to find folders and scripts
permitted to submit under a …
=> Checkout repo

.github/workflows/prod-sync-rpm.yml
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1922023620?check_suite_focus=true
Install required packages
(c) The …
=> Install required packages

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values.yaml
Update Helm version from 1.12.0 to 1.13.0 for ODFE 1.13.0 release
work with modifications, whether created in whole or in …
=> Update Helm version from 1.12.0 to 1.13.0 for ODFE 1.13.0 release

.github/workflows/prod-sync-deb.yml
V313270097
This PR is to improve deb/rpm prod sync workflows
No Need.
work with modifications, whether created in whole or …
=> Improve deb/rpm prod sync workflows

.github/workflows/staging-build-tar.yml, release-tools/scripts/check_plugin.sh
Remove ODFE version dependency in check plugin
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/589963484
(c) …
=> Remove ODFE version dependency in check plugin

.github/workflows/prod-sync-artifacts.yml, release-tools/scripts/manifest.yml
Update manifest to include the new release candidate
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/619247055 …
=> Update manifest to include the new release candidate

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values.yaml
Change version for helm as per the ODFE release 1.13.1
by me, …
=> Change version for helm as per the ODFE release 1.13.1

release-notes/opendistro-for-elasticsearch-release-notes-1.13.1.md
Release notes for 1.13.1
No Test needed. 
by me, under the same …
=> Release notes for 1.13.1

.github/workflows/prod-sync-ami.yml
Fix the script to use right path for od_version and pager.
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/2036275414?check_suite_focus=true
permitted to submit under a different license), as …
=> Fix AMI prod sync script

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
V323155421
This PR is to properly add DCO and guides for contributors to sign off their commits
No Need.
(c) The contribution was provided …
=> Properly adding DCO

release-tools/scripts/manifest.yml
V334961194
This PR is to prepare for Data Prepper 0.8.0 Beta Releases
No Need.
=> Prepare for Data Prepper 0.8.0 Beta Releases

elasticsearch/docker/config/docker-entrypoint.sh
*Issue #, if available:*  https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/696
Instead of dropping to another user, just run 'docker run -u <username>'
* Ran `build-image.sh -v 1.13.1` to download and generate odfe:1.13.1 locally.
* Ran `docker run -p 9200:9200 -p 9600:9600 --rm -it -e cluster.name=banana odfe:1.13.1` to start a single-node cluster. Verified that the cluster started correctly with `curl -XGET https://localhost:9200 -u 'admin:admin' --insecure`
* Ran `docker run -p 9200:9200 -p 9600:9600 --rm -it -e cluster.name=banana -u root odfe:1.13.1 /bin/bash`. Verified that the container did not start. Error message: `Elasticsearch cannot run as root. Please start your container as another user.`
By submitting this …
=> Change docker-entrypoint.sh to fail if the user attempts to run as root.

release-tools/scripts/manifest.yml
ODFE new release 1.13.2 and make TA release candidate
Validated the manifest locally
=> ODFE new release 1.13.2 and make TA release candidate

release-tools/scripts/manifest.yml
Add new build and plugin versions for ODFE 1.13.2 release
Tested manifest locally
=> Add new build and plugin versions for ODFE 1.13.2 release

kibana/docker/build/kibana/config/kibana.yml, kibana/linux_distributions/config/kibana.yml, kibana/macos/config/kibana.yml
Add additional setting to kibana.yml
=> Add additional setting to kibana.yml

kibana/docker/build/kibana/config/kibana.yml, kibana/linux_distributions/config/kibana.yml, kibana/macos/config/kibana.yml
Add comment for Maps Service in Kibana yaml
=> Add comment for Maps Service in Kibana yaml

release-tools/scripts/manifest.yml
Signed-off-by: sreekarjami <sreekarj@amazon.com>
Add RC candidate details to manifest
Tested manifest manually. 
=> Add RC candidate details to manifest

.github/workflows/prod-sync-ami.yml, .github/workflows/staging-build-ami.yml
Modify existing AMI workflows to include ARM64 for AMI
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/720689774
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/720689773 …
=> Modify existing AMI workflows to include ARM64 for AMI

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values-nonroot.yaml, helm/opendistro-es/values.yaml
Change version for helm as per the ODFE release 1.13.2
Tested locally. 
=> Change version for helm as per the ODFE release 1.13.2

release-notes/opendistro-for-elasticsearch-release-notes-1.13.2.md
=> Release notes for 1.13.2

.github/workflows/check-vulnerability-whitesource.yml, standalone-tools/wss-scan.config
Remove security plugins from Whitesource scan and add new creds for the ec2 generation 
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/2384951045?check_suite_focus=true
=> Remove security plugins from Whitesource scan and add new creds for the ec2 generation 

release-notes/opendistro-for-elasticsearch-release-notes-1.13.3.md
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Add odfe 1.13.3 release notes document
=> Add odfe 1.13.3 release notes document

helm/README.md, helm/opendistro-es/Chart.yaml, helm/opendistro-es/values-nonroot.yaml, helm/opendistro-es/values.yaml, release-notes/opendistro-for-elasticsearch-release-notes-1.13.3.md
Update helm to use odfe 1.13.3, keep kibana 1.13.2
=> Update helm to use odfe 1.13.3, keep kibana 1.13.2
