opendistro-for-elasticsearch/opendistro-build

- .gitignore
- helm/opendistro-es/Chart.yaml
- helm/opendistro-es/templates/elasticsearch/elasticsearch-serviceaccount.yaml
- helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
- helm/opendistro-es/templates/elasticsearch/es-client-ingress.yaml
- helm/opendistro-es/templates/elasticsearch/es-client-pdb.yaml
- helm/opendistro-es/templates/elasticsearch/es-config-secret.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-pdb.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-svc.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-pdb.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-service.yaml
- helm/opendistro-es/templates/elasticsearch/master-svc.yaml
- helm/opendistro-es/templates/elasticsearch/role.yaml
- helm/opendistro-es/templates/elasticsearch/rolebinding.yaml
- helm/opendistro-es/templates/kibana/kibana-config-secret.yaml
- helm/opendistro-es/templates/kibana/kibana-deployment.yaml
- helm/opendistro-es/templates/kibana/kibana-ingress.yml
- helm/opendistro-es/templates/kibana/kibana-service.yaml
- helm/opendistro-es/templates/kibana/kibana-serviceaccount.yaml
- helm/opendistro-es/templates/kibana/role.yaml
- helm/opendistro-es/templates/kibana/rolebinding.yaml
- helm/opendistro-es/templates/psp.yml
- helm/opendistro-es/values.yaml
No tests for the Helm chart.
---
Here is a list of changes in this PR:
1) **Added `apiVersion: v1` to `Chart.yaml`, it's a required field**.
2) **Support for Kubernetes 1.16** (contains changes from https://github.com/opendistro-for-elasticsearch/community/pull/143, also can close this issue after merge: https://github.com/opendistro-for-elasticsearch/community/issues/145).
- Fixed apiVersion for Deployment and StatefulSet, because this version was deprecated and removed in Kubernetes 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
- Added selector to Deployment and StatefulSet, which is required with apps/v1 API.
3) **Removed hardcoded `busybox`, use Helm values** (contains changes from …
> Helm chart best practises and fixes

- elasticsearch/linux_distributions/k-NN-lib-buildscripts/build-kNNlib-deb.sh
- elasticsearch/linux_distributions/k-NN-lib-buildscripts/build-kNNlib-rpm.sh
- elasticsearch/linux_distributions/scripts/preInstall-deb.sh
- elasticsearch/linux_distributions/scripts/preInstall-rpm.sh
- elasticsearch/version.json
Updating the preInstall scripts. Initially the scripts were building the kNN lib on the system. Now the scripts are modified to fetch the prebuilt library from s3 and put it in /usr/lib.
Also build scripts are provided for the deb and rpm users if they wish to build the library locally on the system.
> Srivasri pre install scripts

- elasticsearch/linux_distributions/build.gradle
- elasticsearch/linux_distributions/scripts/preInstall-deb.sh
- elasticsearch/linux_distributions/scripts/preInstall.sh
Made the preInstall scripts for deb and rpm common.
The script checks for the presence of kNN lib, if found it deletes the lib and fetches the one in s3 and put it in place.
> Srivasri patch 2

- .github/workflows/build-windows.yml
- elasticsearch/linux_distributions/opendistro-windows-build.sh
- kibana/linux_distributions/opendistro-windows-kibana-build.sh
Instead of copying "bat" files from odfe tar, we are downloading windows oss zip from elastic repo, install plugins and uploading opendistro zip to staging repo.
> Windows Zip Bug Fix

- helm/opendistro-es/templates/_helpers.tpl
- helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
- helm/opendistro-es/templates/kibana/kibana-deployment.yaml
There are no tests for the helm charts
This PR removes the `chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"` label from the selector for the statefulSets and deployments.  With that label on the selector, upgrading the helm chart to a new version will attempt to alter the selector for the sts/deployments and that field is immutable preventing the upgrade from going through.
For reference, an error similar to this one results when attempting a helm chart upgrade from one version to another with this selector present:
```
Error: rpc error: code = Unknown desc = Deployment.apps "opendistro-es-client" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"opendistro-es", "chart":"opendistro-es-1.3.2", "heritage":"Tiller", …
```
> Remove chart label from deployment/sts selector

- helm/opendistro-es/templates/elasticsearch/es-client-pdb.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-pdb.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-pdb.yaml
The existing PodDisruptionBudget templates seem to have a typo in them for the data path. I think this fixes it (or I've mis-understood how the chart is supposed to work).
> Fix the PDB minAvailable reference

- .github/workflows/check_plugin.yml
This PR is to tweak check_plugin.yml so that it can switch targets based on user defined env var PLUGIN_TYPES. It is required for the next improved step of check within build scripts to work.
It can now properly detect the status of a plugin check. If all the necessary plugins are available, return success; else, return failure. The email will still be sent to corresponding teams.
1.7.0 success case:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/108636259
1.8.0 failure case:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/108631070
Chime Message case:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/108759663
The test will show as failure, which is expected, as currently 1.8.0 plugins are not out …
> Modify check_plugin.yml to use user assigned values and chime message (2)

- .github/workflows/check_plugin.yml
This PR is to change the AD plugin with the new naming convention for consistency purposes in 1.8.0 ODFE Version.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/110596674
> Opendistro build 1.8.0 ad naming 1

- .github/workflows/check_plugin_temp.yml
This is the PR to change check_plugin_temp.yml to support user payloads overrides.
It is the second attempt to define the test environment for #165.
Also, some tweaks are added to the script to make it more POSIX compatible.
Test case:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/110912058
Thanks.
> Make check_plugin_temp able to accept user payloads

- helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
Tested on the release 20200520 of Opensuse Kubic.
Fixes issue https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/167
> Fix capability issue when deploying on kubernetes/CRI-O with helm

- .github/workflows/check_plugin_temp.yml
- .github/workflows/test-build-deb-temp.yml
This PR is to add the dynamic trigger of check_plugin workflow and result verification process into the build script of deb distributions.
The pre-requisite here: check_plugin.yml has already been updated here: #161 #172.
Yes Alert:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/112768527
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/112768696
No alert:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/112767077
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/112767294
> Improve deb build script to call check_plugin workflow with results

- .github/workflows/test-build-deb.yml
This PR is to set email alert to be default off for deb build script.
> Set email alert to be default off

- .github/workflows/test-webhook-build-docker.yml
Replaced continue-on-error to if: always() so that we can notice if IT fails for any plugin.
> Replace condition for IT to show errors

- .github/workflows/test-build-windows.yml
Observed the workflow [failing](https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/712623097?check_suite_focus=true) due to jdk version
> Java version upgraded to 14

- helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
- helm/opendistro-es/values.yaml
This adds support for disabling sysctl which requires privilege
which isn't supported on all clusters.
> Support disabling sysctl

- elasticsearch/docker/build/elasticsearch/bin/docker-entrypoint.sh
Fixes https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/10
**This pullrequest needs a test** (and some documentation)
Adds a env-variable in docker entrypoint script to decide whether to execute demo configuration for the security plugin (as it will try to overwrite any existing mounted configuration)
> Add check for DISABLE_INSTALL_DEMO_CONFIG

- helm/opendistro-es/templates/psp.yml
See [this issue](https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/228)
Deployed with 
```
helm install local-opendistro ./opendistro-build/helm/opendistro-es \
>        --set kibana.ingress.enabled=true \
>        --set kibana.ingress.hosts={opendistro.local} \
>        --set elasticsearch.client.ingress.enabled=false \
>        --set kibana.replicas=1 \
>        --set elasticsearch.master.replicas=1 \
>        --set elasticsearch.client.replicas=1 \
>        --set elasticsearch.data.replicas=1 \
>        --set elasticsearch.master.storageClassName="local-default-storage" \
>        --set elasticsearch.master.storage="10Gi" \
>        --set elasticsearch.data.storageClassName="local-default-storage" \
>        --set …
```
> Added support for podsecuritypolicies. Added the capability SYS_CHROOT.

- .github/scripts/check_plugin.sh
- .github/workflows/check_plugin.yml
- .github/workflows/check_plugin_old.yml
- .github/workflows/release-sync-tar.yml
- .github/workflows/release-sync-windows.yml
- .github/workflows/test-build-deb.yml
- .github/workflows/test-build-rpm.yml
- .github/workflows/test-build-tar.yml
- .github/workflows/test-build-windows.yml
- elasticsearch/linux_distributions/opendistro-tar-build.sh
- elasticsearch/windows/opendistro-windows-build.sh
- kibana/README.md
- kibana/linux_distributions/opendistro-kibana-build.sh
- kibana/windows/opendistro-windows-kibana-build.sh
This PR is to reduce the complexity of the scripts and workflows in check_plugin and windows/tar workflows/scripts.
Also, the name of the script in kibana folder ./generate-pkg.sh has been renamed to ./opendistro-kibana-build.sh for consistent naming convention.
------
- check_plugin:
- success case: 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/125217569
- failure case: 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/125212578
- windows:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/126417132
- tar:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/126417134
The bin directories in elasticsearch and kibana folder will be removed later, it is kept now until we make …
> Reduce scripts complexity in check plugins/windows/tar

- .github/workflows/release-sync-ami.yml
- .github/workflows/test-build-ami.yml
- .github/workflows/test-build-deb.yml
- .github/workflows/test-build-rpm.yml
- kibana/linux_distributions/opendistro-kibana-build.sh
This PR is to reduce the complexity of the deb and rpm workflows/scripts.
------
- deb:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/128969651
- rpm:
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/128988343
The bin directories in elasticsearch and kibana folder will be removed later, it is kept now until we make changes to all the scripts for backward compatibility.
> Reduce scripts complexity in deb and rpm workflows

- helm/README.md
- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-security-config.yaml
- helm/opendistro-es/values.yaml
This PR simplifies  security secrets configurations. It allows users to specify the values of  config.yml, action_groups.yml, internal_users.yml, roles.yml, roles_mapping.yml  in values.yaml file instead of creating different secrets for each.
> Simplify security secrets configurations

- elasticsearch/linux_distributions/opendistro-tar-build.sh
- kibana/linux_distributions/opendistro-kibana-build.sh
This PR is to tweak and fix the checksum generation for tar, raised in [this issue](https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/81) by the community.
It also improves the scripts a bit here.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/131557160
> Tweak and fix the checksum generation for tar

- download_kibana_plugins.sh
- download_plugins.sh
- elasticsearch/docker/Makefile
- kibana/docker/Makefile
This PR is to add the missing simplification changes to docker plugin scripts. It is somehow missed in the improvement for Infra Issue [#140](https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/140).
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/133702863
> Add the missing simplification changes to docker plugin scripts

- elasticsearch/linux_distributions/opendistro-tar-build.sh
- elasticsearch/linux_distributions/opendistro-tar-install.sh
Move knn lib to tarball distribution, and use install script to move this lib to right place at runtime. This is the short solution to avoid internet connectivity issue at runtime.
Tested it locally. The lib will be included in tarball distribution. And the es service can start up successfully. But no testing for knn feature. This will be included in the building workflow
> Move KNN lib to tarball distribution

- elasticsearch/linux_distributions/opendistro-tar-install.sh
This PR is to follow up with the current KNN plugin changes to further optimize the process.
Instead of using /usr/lib to store the dylib file for KNN, we will export it to LD_LIBRARY_PATH (LINUX) as the lib file already has the correct naming convention to load from non-root owned directories. Also, macOS will use DYLD_LIBRARY_PATH here.
This would help with setups on shared (multi tenant) clusters without root.
This PR is depend on another PR here: https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/269
[knnlib_ld_nonroot.log](https://github.com/opendistro-for-elasticsearch/opendistro-build/files/4795511/knnlib_ld_nonroot.log)
> Use custom lib path to replace /usr/lib

- .github/workflows/check_plugin.yml
This PR is to enable 1.9.0 schedules for check_plugin workflow.
> Enable 1.9.0 schedules for check_plugin workflow

- .github/workflows/test-build-docker-ci.yml
- download_kibana_plugins.sh
- download_plugins.sh
This PR is to release the CI Docker Test Images for Plugin Teams to run tests before all the plugins artifacts are available.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/144181876
(ES failed because KNN 1.9.0 not available as of now)
> Release CI Docker Test Images for Plugin Teams

- .github/scripts/userdata.sh
- .github/templates/odfe-testing-cluster-template.json
- .github/workflows/test-cluster-delete.yml
- .github/workflows/test-cluster-set-up.yml
This PR adds infrastructure set up for testing domains that the plugins team will use during the staging stage of the release.
- [Tested Set up](https://github.com/gaiksaya/opendistro-build/actions/runs/146579537)
- [Tested tear down](https://github.com/gaiksaya/opendistro-build/actions/runs/146610299)
Necessary secrets will be added to the repo.
**Note**: The delete workflow will be used to delete all the testing clusters (mostly after the release).
> Adding testing domain setup and teardown infra

- .github/templates/odfe-testing-cluster-static-domain-template.json
- .github/workflows/test-cluster-static-domain-set-up.yml
Adding workflow and template for static domain testing cluster. The purpose of this PR is to have static domains for testing cluster throughout the release process. The workflow will just register the EC2 to the appropriate target groups and load balancers.
The ELBs and Target groups have already been added in the AWS account. Will add the ELB links in the quip for plugin teams to refer
[Tested](https://github.com/gaiksaya/opendistro-build/runs/809776285?check_suite_focus=true)
> Adding infra for testing clusters with static domain

- kibana/docker/templates/Dockerfile.j2
- kibana/linux_distributions/opendistro-kibana-build.sh
This is a temp solution to fix the kibana startup issue:
the "injex.js" file is missing in the brace node module of kibana 7.8.0 OSS, but opendistro kibana plugins need it.
> Fix the kibana startup issue with temp solution

- .github/workflows/test-build-windows.yml
This PR is to make windows workflow use python to eval version-info, since windows does not work with env utility like on *nix systems.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/151886922
> make windows workflow use python to eval version-info

- .github/workflows/test-cluster-static-domain-set-up.yml
Added new function that will create stack depending upon the trigger event. The workflow will run for both events i.e. repository dispatch and schedule. For schedule it will create/update all the 6 combinations of the testing domains. For repository dispatch I have kept it mandatory to pass the parameters for now
Tested with [repository_dispatch](https://github.com/gaiksaya/opendistro-build/runs/820286866?check_suite_focus=true)
Tested with [schedule](https://github.com/gaiksaya/opendistro-build/actions/runs/152041282)
> Adding functionality for schedule run

- elasticsearch/docker/build/elasticsearch/bin/docker-entrypoint.sh
- elasticsearch/docker/templates/Dockerfile.j2
This small change adds support for packaging performance analyzer + RCA in ODFE.
Summary of changes:
* Separates the agent from the plugin location after install as the agent(with RCA) and the plugin are bundled together.
* Updates path to PA's conf files in docker entrypoint.
> Add support for shipping performance analyzer with RCA

- .github/workflows/test-build-tar.yml
This PR is to add path.repo parameters for ISM integTest to take snapshots.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/152112675
>  Add path.repo for ISM integTest to take snapshots 

- .github/workflows/test-build-docker.yml
This PR is to tweak docker with correct ISM integTest setups, with path.repo set for snapshots during integTest process.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/153070674
> Tweak docker with correct ISM integTest setups

- .github/workflows/release-sync-ami.yml
- .github/workflows/test-build-ami.yml
This PR is to remove old bin path for version-info scripts.
> Remove old bin path for version-info scripts

- elasticsearch/docker/templates/Dockerfile.j2
https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/34
https://github.com/opendistro-for-elasticsearch/performance-analyzer/pull/146
https://github.com/opendistro-for-elasticsearch/performance-analyzer-rca/pull/271
Move PA/RCA files to subdir owned by elasticsearch user (Support)
*Tests:*
[image](https://user-images.githubusercontent.com/65193828/87365444-3d975f80-c544-11ea-8ad0-4a2d4d81320a.png)
*Code coverage percentage for this patch:*
> Move PA/RCA files to subdir owned by elasticsearch user (Support)

- .github/scripts/setup_runners_service.sh
- .github/workflows/staging-build-docker.yml
This is part3 of "Workflow Consistency / Simplification Updates in All Workflows".
Here is part1: https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/331
Here is part2: https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/335
This PR is to improve workflow consistency / simplification updates in all workflows.
* Unifying naming conventions of workflow files here
* Unifying workflow job names with RPM one for references
* Simplify workflow integTests by utilizing the setup_runner_service.sh scripts
* Add a setup_runner_service_windows powershell script for windows env
(windows GitHub runner default shell is set to powershell: https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/)
* DOCKER: …
> Workflow Consistency / Simplification Updates in All Workflows - Part3

- .github/workflows/check-plugin.yml
- .github/workflows/check-version-upgrade.yml
- .github/workflows/prod-sync-ami.yml
- .github/workflows/prod-sync-deb.yml
- .github/workflows/prod-sync-tar.yml
- .github/workflows/prod-sync-windows.yml
- .github/workflows/staging-build-ami.yml
- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker-ci.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
- .github/workflows/test-cluster-delete.yml
- .github/workflows/test-cluster-set-up.yml
- .github/workflows/test-cluster-static-domain-set-up.yml
This PR is to replace ubuntu-latest with ubuntu-18.04 tags now.
> Replace ubuntu-latest with ubuntu-18.04 tags now

- .github/workflows/staging-build-docker-ci.yml
This PR is to enable daily docker ci builds by using the github workflow crontab schedules
No need as it is just enabling a schedule
> Enable docker ci builds to run per schedule

- bin/plugins-info
- bin/plugins.json
- bin/version-info
- bin/version.json
- download_kibana_plugins.sh
- download_plugins.sh
- elasticsearch/linux_distributions/build.gradle
- elasticsearch/linux_distributions/opendistro-tar-build.sh
- elasticsearch/windows/opendistro-windows-build.sh
- kibana/linux_distributions/opendistro-kibana-build.sh
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/264
------
This PR is to cut the versions of the plugins after a final distro builds so we can lock them up for rebuilds later.
In bin/version.json:
* if is_cut is false, plugin downloads/installation will take the latest version from S3 bucket
* if is_cut is true, plugin downloads/installation will take the hard-coded version in bin/plugins.json
* plugins-info and plugins.json affect these scripts:
```
download_kibana_plugins.sh
download_plugins.sh
elasticsearch/linux_distributions/opendistro-tar-build.sh
elasticsearch/linux_distributions/build.gradle
elasticsearch/windows/opendistro-windows-build.sh
kibana/linux_distributions/opendistro-kibana-build.sh
```
------ …
> ODFE Final Plugin Version Cut in versions.json and plugins.json

- .github/workflows/staging-build-docker-ci.yml
This PR is to disable CI docker daily builds as we have completed ODFE 1.10.0 Step 1&2 and does not need this CI docker image anymore
No need as we are just disabling the schedules in the workflows
> Disable CI Docker Daily Builds for ODFE 1.10.0

- .github/workflows/check-plugin.yml
This PR is to disable the check_plugin workflow daily checks as Step 1&2 of ODFE 1.10.0 are completed.
No need to as we are just disable the scheduling
> Disable check_plugin workflow daily checks for ODFE 1.10.0

- .github/scripts/check_plugin.sh
- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- bin/plugins-info
- bin/plugins.json
This PR is to resolve check_plugins.sh issues as we update plugins.json in #357. 
The check_plugin.sh relies on plugins-info and plugins.json to provide plugin lists.
Due to the changes in #357 the usage and formats of the plugins-info & plugins.json is changed now.
However, check_plugin.sh did not make corresponding changes, thus fail the check due to not able to obtain the plugin list.
This PR fixed the issue by correctly calling plugins-info in check_plugin.sh, and the related workflows.
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/233601325
The failure is only for email not for plugin checks, will fix email in a …
> Resolve check_plugins.sh issues as we update plugins.json in #357

- .github/scripts/setup_runners_service.sh
The SQL integration tests are currently failing due to too many script compilations. The exact error message is:
`{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.context.field.max_compilations_rate] setting","bytes_wanted":0,"bytes_limit":0,"durability":"TRANSIENT"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"elasticsearch-sql_test_index_account","node":"sM9eduqeRKOVqk7JbU0zIA","reason":{"type":"general_script_exception","reason":"Faile …
> Increase the maximum script compilation rate in setup_runners_service.sh

- .github/scripts/setup_runners_service_windows.ps1
This PR is to fix an incorrect kibana url for windows version in service powershell script.
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1064392251?check_suite_focus=true#step:5:130
The test is supposed to fail, it only test to prove kibana started as download is complete with the fixed URL.
>  Fix Incorrect Kibana URL in Windows Service Scripts

- helm/opendistro-es/templates/elasticsearch/es-client-deploy.yaml
- helm/opendistro-es/templates/elasticsearch/es-data-sts.yaml
- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
- helm/opendistro-es/templates/kibana/kibana-deployment.yaml
- helm/opendistro-es/values.yaml
Allow the consumer to specify an alternative docker registry in the helm chart. This allows installing OpenDistro in non-public environments that rely on private docker registries. Keep the default as the standard implicit docker registry: docker.io
Image in `templates/elasticsearch/es-data-sts.yaml` with default values:
```yaml
image: docker.io/amazon/opendistro-for-elasticsearch:1.9.0
```
Image in `templates/elasticsearch/es-data-sts.yaml` with setting `global.registry=my.registry.org` in values:
```yaml
image: my.registry.org/amazon/opendistro-for-elasticsearch:1.9.0
```
> allow customizing docker registry

- bin/version.json
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/271
This PR is to bump ODFE/ES Versions to 10.0.1/7.9.1 for ODFE 1.10.1 Release
No need as it is just a version bump.
> Bump ODFE/ES Versions to 10.0.1/7.9.1 for ODFE 1.10.1 Release

- helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml
N/A
Current behavior:
When the `securityconfig` is disabled, `extraVolumeMounts` of master nodes will also be disabled.
Expected behavior:
When the `securityconfig` is disabled, `extraVolumeMounts` of master nodes will remains.
This PR allows master nodes to have extra volume mounts when `securityconfig` is disabled.
I am not sure how to test Helm charts properly, but I have tested it in my local environment.
> Helm master nodes allows extraVolumeMounts when securityconfig disabled 

- .github/PULL_REQUEST_TEMPLATE.md
This PR is to update PR template to ask user for HELM documentation updates when needed
Not Needed as it is a PR template update
> Update PR template to ask user for Helm documentation updates when needed

- .github/workflows/staging-build-windows.yml
This PR is to correct alerting integTest to use alerting repository
No Need as it is just a repo correction, no function changes
> Correct alerting integTest to use alerting repository

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
- .github/workflows/test-cluster-static-domain-set-up.yml
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/256
This PR is to enable schedule workflow for distro builds and test domain setup in ODFE 1.10.1
No need since we are just enabling the schedules
> Enable schedule workflow for distro builds and test domain setup in ODFE 1.10.1

- bin/releasenotes-orig-urls.txt
- bin/releasenotes.sh
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/268
This PR is to Improve release notes script sorting and sed logic
* The sorting mechanism will consider special chars, so -d is used as dictionary order to only consider blank and alphanumeric characters; also, use -f to ignore case in the process
* The original sed logic to replace ### with ## is flawed as it also removes spaces if the category name has it (i.e. "Bug Fixes" or "Breaking Changes"), so fix it with a simply removal of leading "#"
It is a local script and works with local runs …
> Improve release notes script sorting and sed logic

- kibana/docker/build/kibana/config/kibana.yml
- kibana/linux_distributions/config/kibana.yml
This PR is to add new cookie settings for security kibana plugins 2.0 framework when https is disabled
The 2.0 framework is forcing 1 to 1 match between https and cookie settings
Our kibana is default to http, thus requires cookie to be insecure
Users can choose to enable https and disable this config
$ find . -name kibana.yml
./kibana/docker/build/kibana/config/kibana.yml
./kibana/linux_distributions/config/kibana.yml
Manually tested on a EC2 instance, no automatic test yet.
**https://github.com/opendistro-for-elasticsearch/opendistro-b …
> Add new cookie settings for security kibana plugins 2.0 framework when https is disabled

- .github/scripts/setup_runners_service.sh
- .github/scripts/setup_runners_service_windows.ps1
Add opendistro_security.cookie.secure: false to service scripts settings for TAR/DEB/RPM/DOCKER/WINDOWS
This is a follow-up PR to https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/397
Service script will add this settings no matter what
It will not take effect in security kibana 1.0 framework, and it will take effects if it does not present in security kibana 2.0 framework
No way to test as integration test does not allow us to access 5601 port on github runners …
> Add opendistro_security.cookie.secure: false to service scripts settings for TAR/DEB/RPM/DOCKER/WINDOWS

- .github/scripts/setup_runners_service.sh
- .github/scripts/setup_runners_service_windows.ps1
Reverts opendistro-for-elasticsearch/opendistro-build#398
It is not required anymore as this is already a default in #397, and adding it for the second time will cause issues:
```
FATAL CLI ERROR YAMLException: duplicated mapping key at line 36, column 1:
```
> Revert "Add opendistro_security.cookie.secure: false to service scripts settings for TAR/DEB/RPM/DOCKER/WINDOWS"

- release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/255
This PR is to add ODFE 1.10.1 distro release notes
No need as it is adding a release notes
> Add ODFE 1.10.1 distro release notes

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
- .github/workflows/test-cluster-static-domain-set-up.yml
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/253
This PR is to disable daily schedule for staging artifacts and test domain building process
No need as it just disables the scheduling
> Disable daily schedule for staging artifacts and test domain building process

- bin/plugins.json
- bin/version.json
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/253
This PR is to apply Version Cuts and Locks to ODFE 1.10.1 plugins
We will build final distros with these locked versions
> Apply Version Cuts and Locks to ODFE 1.10.1 plugins

- .github/workflows/check-version-upgrade.yml
Tell wget to run in quiet mode
Workflow succeeded and has ~4500 fewer log lines: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1184349997?check_suite_focus=true
> Make check-version-update logs less verbose

- release-notes/opendistro-for-elasticsearch-release-notes-1.10.1.md
https://github.com/opendistro/for-elasticsearch-docs/pull/312
Update opendistro-for-elasticsearch-release-notes-1.10.1.md to label kibana cookie change as a breaking change and link instruction page to users
> Update opendistro-for-elasticsearch-release-notes-1.10.1.md to label kibana cookie change as a breaking change and link instruction page to users

- release-tools/cloudformation/plugin-iam-users.yml
Add a CloudFormation template for managing the IAM users we allow to upload plugin artifacts to the staging bucket.
Manually tested in a burner account. Verified that users are created correctly. Used the IAM policy simulator to verify that they can put to the right locations and cannot get or delete objects, or create or delete buckets.
> Add CloudFormation template for managing plugin IAM users

- .github/workflows/check-plugin.yml
Activate cron job to get alerts regarding plugin availability as this is release time. This will send alerts to slack room
Not required. Just activating the scheduled cron job
> Activate cronjob to get alerts regarding plugin availability

- bin/plugins.json
- bin/version.json
Lock plugin versions for ODFE 1.11.0. Also add kibana-notebooks and change sql-workbench to query-workbench.
> Lock plugin versions for 1.11.0 and add kibana-notebooks

- .github/workflows/check-plugin.yml
Disable plugin availability check cron
> Disable plugin availability bot

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
sql-workbench has been renamed to workbench
> Update staging workflows to use workbench instead of sql-workbench

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
We don't need Java 15 for the 1.11.0 release.
> Remove Java 15 from the test matrix

- .github/scripts/setup_runners_service.sh
The line in setup_runners_service.sh that added the max_compilations_rate was failing with "permission denied". This change fixes the issue.
I will add a follow-up PR that adds `set -e` so that these issues are caught sooner. There are a bunch of things that fail right now if I add `set -e`, so I'm not including it in this change.
Manually verified that the elasticsearch.yml file is correctly updated.
> Fix max_compilations_rate setting for deb/rpm tests

- standalone-tools/wss-scan.config
Remove the sql plugin which have been combined to a single repo and also remove kibana-reports repo from the wss-scan.config
No Test needed
> Remove the ODFE Repos which are not need to be scanned for vulnerability 

- bin/releasenotes.sh
GNU seq defaults to a positive increment, even when 'last' is smaller than 'first'
> Releasenotes.sh: Explicitly tell 'seq' to count down

- bin/releasenotes.sh
None
This PR is to properly escape the & ampersand in release notes
It also change wget output from none to limited verbose so at least user can see what is wrong with the retrieving of release notes from GitHub here.
None
> Improve releasenotes.sh to properly escape ampersand in release notes

- .github/workflows/check-vulnerability-whitesource.yml
- helm/opendistro-es/values.yaml
Change the Vulnerability workflow to run on ec2 , this allows all the child processes to be completed. At present the GitHub runner is unable to complete all the scanning of the ODFE Repos due to less resources. 
Scan test result : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/336617044
> Change the Vulnerability workflow to run on ec2 

- .github/workflows/codeql-analysis.yml
This change is to add CodeQL scan for the GitHub Repo. Should allow us to scan PR when submitted for review. 
> Add CodeQL for Scanning ODFE Build Repo

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/476
P41846943 
Update the AD Integration Test command for release workflows as per the above issue
No way to test it right now since we don't have ODFE 1.12.0 built yet.
> Update the AD Integration Test command for build workflows

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- bin/version.json
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/480
P41850229 
Fix the breaking change for workflows using cypress-io/github-action@v1.
Somewhere at the back version 1 of the action is using set-env which is deprecated now. It fails with same [error](https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1421506285?check_suite_focus=true#step:12:23)
The issue has been fixed in v2.3.1+ as per the comment [here](https://github.com/cypress-io/github-action/issues/206#issuecomment-715402894)
Using v2.5.0 as per https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/480
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1427236480?check_suite_focus=true …
> Update cypress-io/github-action v1 to v2.5.0

- bin/plugins.json
Zip name error fixed in this PR for **opendistroNoteboooksKibana**
Not required
> Fix kibana notebooks zip name

- kibana/linux_distributions/scripts/post_install.sh
V286471153
This PR is to add a OR condition to skip chown commands on ./optimize folder if not exist
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/399329811
> Add a OR condition to skip chown commands on ./optimize folder if not exist

- .github/workflows/staging-build-docker.yml
- elasticsearch/docker/Makefile
- kibana/docker/Makefile
v286570428
This PR is to remove virtualenv requirements for docker building process as we do not need unit testings
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/399499652
> Remove virtualenv requirements for docker building process as we do not need unit testings

- .github/workflows/staging-build-deb.yml
- .github/workflows/staging-build-docker.yml
- .github/workflows/staging-build-rpm.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-build-windows.yml
- .github/workflows/test-cluster-static-domain-set-up.yml
P42248533
Activate cronjob schedule for all staging workflows so that recent artifacts are picked up and build daily until testing phase.
Not required
> Activate cronjob schedule for all staging workflows

- .github/scripts/setup_runners_service_windows.ps1
- .github/workflows/staging-build-windows.yml
P42402699
`path.repo` settings is missing in the windows installation script due to which ISM IT are failing. This PR fixes it for non-sec part. Might need to refactor the logic later for with security part.
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1528207675?check_suite_focus=true
> Add path.repo settings to windows installation script

- kibana/docker/build/kibana/config/kibana.yml
- kibana/linux_distributions/config/kibana.yml
V291643202
This PR is to disable showInsecureClusterWarning for Kibana 7.10 configurations
Test with local env and clusters
> Disable showInsecureClusterWarning for Kibana 7.10 configurations

- .github/workflows/staging-build-ami.yml
v290419891
This PR is to change SG for AMI to the default SG to default VPC
https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/1554062177?check_suite_focus=true
The instance is created without issues now so I cancel the run
> Change SG for AMI to the default SG to default VPC

- .github/workflows/check-vulnerability-standalone.yml
- .github/workflows/check-vulnerability-whitesource.yml
Change Daily WhiteSource scan workflow to provide ami id to the setup runners as per the new script, and change standalone WhiteSource to show project url
Standalone : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/470126253
Daily scan : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/470070352
> Change Daily WhiteSource scan workflow to provide ami id and change standalone WhiteSource to show project url

- release-tools/scripts/staging-copy-artifacts.py
Add plugin base name to the latest plugin search function in the storing artifact script
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/479047750
> Add plugin base name to the latest plugin search function in the storing artifact script

- .github/workflows/staging-copy-artifacts.yml
- release-tools/scripts/staging-copy-artifacts.py
*Description of changes:* Change the storing artifact script to pick the artifact with the highest build number instead of the last modified. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/481459695
> Change the storing artifact script to pick the artifact with the highest build number

- .github/workflows/staging-build-windows.yml
- elasticsearch/windows/opendistro-windows-build.sh
- kibana/windows/opendistro-windows-kibana-build.sh
remove install4j license info from the windows staging build script and move it to git secrets
Test will not pass due to the new ODFE structure
> remove license info from the windows build script and move it to git secrets

- helm/opendistro-es/values.yaml
Out of the box calls to the Elastic client ingress can fail with the following error: `received plaintext http traffic on an https channel, closing connection`
See for example: https://discuss.elastic.co/t/elasticsearch-with-ingress-received-plaintext-http-traffic-on-an-https-channel/246549
To prevent this, an annotation is necessary that depends on the Ingress Controller used (nginx-ingress or ingress-nginx)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Include Ingress annotations for HTTPS backend

- .github/workflows/prod-sync-rpm.yml
- elasticsearch/linux_distributions/rpm-signing.sh
P40553676
This PR is to tweak rpm signing to make it more robust and work with prod sync
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/510689634
> Tweak rpm signing to make it more robust and work with prod sync

- .github/workflows/staging-build-tar-arm64.yml
- .github/workflows/staging-build-tar.yml
- .github/workflows/staging-test-tar-arm64.yml
- release-tools/scripts/manifest.yml
- release-tools/scripts/setup_runners_service.sh
Add new IT workflow for ARM64 (TAR) and change the setup runner service script to allow multi arch TAR. Change the async plugin to true for release candidate. 
X64 (TAR):https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/529147838
ARM64 (TAR): https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/529105596
> Add new IT workflow for ARM64 (TAR) and change the setup runner service script to allow multi arch TAR

- elasticsearch/linux_distributions/deb-signing.sh
- release-tools/scripts/manifest.yml
V313270097
This PR is to add new data prepper staging location and comment out debs sync back to prod bucket.
No Need.
> Add new data prepper staging location and comment out debs sync back to prod bucket

- .github/workflows/prod-sync-data-prepper.yml
- .github/workflows/staging-build-data-prepper.yml
- release-tools/scripts/manifest.yml
V311401608
This PR is to make DataPrepper work with new env
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/538405093
> Make DataPrepper work with new env

- .github/workflows/staging-test-rpm-arm64.yml
- release-tools/scripts/setup_runners.sh
V313743037
This PR is to make RPM ARM64 with integTest running on new runner
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/541914789
> Make RPM ARM64 with integTest running on new runner

- .github/workflows/check-plugin.yml
Disable schedule run of check plugin workflow
> Disable schedule run of check plugin workflow

- .github/workflows/staging-build-windows.yml
- kibana/windows/opendistro-windows-kibana-build.sh
V313270097
This PR is to make kibana windows work with new tar linux naming convention
No Need.
> Make kibana windows work with new tar linux naming convention

- .github/workflows/staging-test-tar-arm64.yml
- .github/workflows/staging-test-tar-x64.yml
V313270097
This PR is to remove needs for tar x64 integTests
No Need.
> Remove needs for tar x64 integTests

- release-tools/scripts/manifest.yml
V313270097
This PR is to add missing deb/rpm in the manifest for knnlib
No Need.
> Add missing deb/rpm in the manifest for knnlib

- .github/workflows/test-cluster-static-domain-set-up.yml
- release-tools/templates/odfe-testing-cluster-static-domain-template.json
P44184603
Having muti-AZ config on load balancers lead to delay in response time as there are no active instances in that AZ. Hence hard-coding the AZ as per distribution
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/549790286
> Add single AZ config to increase response time in test clusters

- .github/workflows/staging-test-deb-arm64.yml
- .github/workflows/staging-test-rpm-arm64.yml
- release-tools/scripts/userdata.sh
V313270097
This PR is to add arm64 as parameter for deb/rpm workflows and update the architecture for test domains
No Need.
> Add arm64 as parameter for deb/rpm workflows and update the architecture for test domains

- .github/workflows/prod-sync-artifacts.yml
- .github/workflows/prod-sync.yml
- release-tools/scripts/prod-sync-artifacts.py
New prod sync script and prod sync workflow to copy artifacts from staging to Prod. 
Production sync : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/548748559
Validation : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/548719918
Result with build number : https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/555982110
To Do:
Move [these](https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/601/files#diff-88d26d5ff5ff712d17293d09df648a43bb4e08b128012a81636fe5f4af62635eR197-R212) lines to manifest.yml in future
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> New prod sync script and prod sync workflow

- .github/workflows/staging-test-deb-arm64.yml
- .github/workflows/staging-test-rpm-arm64.yml
- .github/workflows/staging-test-rpm-x64.yml
- .github/workflows/staging-test-tar-arm64.yml
remove the IM dependency in the cleanup job for provisioned runners
No test needed
work with modifications, whether created …
> remove the IM dependency in the cleanup job for provisioned runners

- .github/workflows/check-vulnerability-whitesource.yml
- standalone-tools/wss-scan.config
- standalone-tools/wss-unified-agent.config
Remove situp from daily scan and add go version 1.14 for whitesource scanning. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/572463631
permitted to submit under a different license), as …
> Remove situp from daily scan and add go version 1.14 for whitesource scanning 

- .github/workflows/staging-test-deb-arm64.yml
- .github/workflows/staging-test-deb-x64.yml
- .github/workflows/staging-test-docker-x64.yml
- .github/workflows/staging-test-rpm-arm64.yml
- .github/workflows/staging-test-rpm-x64.yml
- .github/workflows/staging-test-tar-arm64.yml
- .github/workflows/staging-test-tar-macos-x64.yml
- .github/workflows/staging-test-tar-x64.yml
- .github/workflows/staging-test-windows-x64.yml
_Issue #, if available:_
https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/673
_Description of changes:_
Adds integration test for Asynchronous search plugin
_Test Results:_ 
- Docker: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/659051242
- Windows: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/640937606
- RPM: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/640981415
- DEB: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/640724858
-  Mac-os: https://github.com/opendistro-for-elasticsearch/opendistro-build/runs/2126653904?check_suite_focus=true
-  Tarball: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/640788067 …
> Add integration test for async plugin with security disabled

- elasticsearch/linux_distributions/opendistro-onetime-setup.sh
- elasticsearch/linux_distributions/opendistro-run.sh
- elasticsearch/linux_distributions/opendistro-tar-install.sh
*Issue #, if available:* #696
Split into opendistro-onetime-setup.sh and opendistro-start.sh.
This change is to ensure that one-time activities, such as installing the demo security config, happen once. This is especially useful for Docker images where we can run the one-time script as part of the Docker build.
opendistro-tar-install.sh invokes opendistro-onetime-setup followed by opendistro-start so that existing scripts that use opendistro-tar-install will continue to work the same as they did before this change.
*Test Results:* Manually tested with a work-in-progress Docker image. Able to install and start a node on Amazon Linux 2.
Also ran "setup_runners_service.sh" on my desktop. The service came up successfully.
By submitting this pull request, I confirm …
> Split opendistro-tar-install.sh into two pieces

- helm/opendistro-es/values.yaml
#687 
Lines 175 to 181 are separated by 3 spaces, so change to 2 spaces.
By configuring Security Configuration normally, it is successful to install helm by configuring oidc backend.
> Indentation bug fix in values.yaml : Security Configuration

- .github/workflows/staging-odfe-cli.yml
- release-tools/scripts/manifest.yml
Change version of ODFE CLI in manifest in regard to its release. 
https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/669319678
> Change version of ODFE CLI in manifest

- elasticsearch/linux_distributions/opendistro-tar-install.sh
*Description of changes:* Revert the change to opendistro-tar-install.sh made in https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/697
staging-build-tar: Success. https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/684150511
staging-test-tar-x64: Alerting failed, all others pass: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/684174020
staging-test-tar-arm64: Alerting and IM failed, all others pass: https://github.com/opendistro-for-elasticsearch/opendistro-build/actions/runs/684174021
Test failures appear to be unrelated to this change. …
> Roll back change to opendistro-tar-install.sh so existing workflows can run

- elasticsearch/docker/dockerfiles/AL2.dockerfile
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/696
Adds an AmazonLinux2-based Dockerfile. There are a couple of upcoming changes that will work with this one:
1. A script to copy the ODFE tarball and config files into a working directory and invoke the Docker build
2. A shiny new docker-entrypoint.sh that doesn't use supervisord to start the performance analyzer agent
This change will not be merged until all three pieces are in place.
*Test Results:* Manually started a container and verified that elasticsearch works.
**https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/REA …
> Add AmazonLinux2 Dockerfile

- elasticsearch/docker/build-image.sh
- elasticsearch/docker/config/docker-entrypoint.sh
- elasticsearch/docker/config/elasticsearch.yml
- elasticsearch/docker/config/log4j2.properties
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/696
Remove security demo config setup. This is pre-installed in the Docker image.
Comment out performance analyzer startup code because it uses supervisord. This will be replaced with something that is not supervisord.
* Ran `build-image.sh -v 1.13.1` to download and generate odfe:1.13.1 locally.
* Ran `docker run -p 9200:9200 -p 9600:9600 --rm -it -e cluster.name=banana odfe:1.13.1` to start a single-node cluster.
* `curl -XGET https://localhost:9200 -u 'admin:admin' --insecure` results:
`
{ 
"name" : "8aa2e7ca55ff",
"cluster_name" : "banana",
"cluster_uuid" : "sxwp-1kRR7yszuDFVo2xmw",
"version" : {
"number" : "7.10.2",
"build_flavor" : "oss", …
> Add AL2 Docker build script and configuration files

- elasticsearch/docker/config/docker-entrypoint.sh
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/696
If users want to run a custom command then they can use 'docker run --entrypoint'
* Ran `build-image.sh -v 1.13.1` to download and generate odfe:1.13.1 locally.
* Ran `docker run -p 9200:9200 -p 9600:9600 --rm -it -e cluster.name=banana odfe:1.13.1` to start a single-node cluster. with no arguments. Verified that the cluster started correctly with `curl -XGET https://localhost:9200 -u 'admin:admin' --insecure`
* Ran `docker run -p 9200:9200 -p 9600:9600 --rm -it -e cluster.name=banana odfe:1.13.1 /bin/bash`. Verified that the `/bin/bash` command was ignored and the cluster started correctly with `curl -XGET https://localhost:9200 -u 'admin:admin' …
> Remove ability to run custom commands from docker-entrypoint.sh

- elasticsearch/docker/dockerfiles/AL2.dockerfile
The BUILD_DATE arg changes every build and breaks the cache. Moving the ARGs to just before they're needed minimizes the amount of cache-busting that goes on.
*Test Results:* Ran the build twice, verified that the second one used the cache.
> Move Dockerfile ARG statements so they don't bust the cache every time

- elasticsearch/docker/config/docker-entrypoint.sh
- elasticsearch/docker/config/performance-analyzer.properties
- elasticsearch/docker/dockerfiles/AL2.dockerfile
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/696
Rip out the supervisord stuff from the docker-entrypoint.sh script and replace it with bash job control.
The entry point starts up the elasticsearch and performance analyzer processes, then waits. If either process terminates then the other one is killed and the container exits. If a SIGTERM (e.g. from `docker container stop`) or SIGINT (e.g. from a ctrl-c) is sent to the script then it will kill both processes.
The idea here is that the container environment is responsible for spinning up a new container instance if the old one fails. There is no need to run supervisord within the container to restart processes.
The performance analyzer startup command is taken …
> Replace supervisord with bash job control so that we can certify the AmazonLinux Docker image

- release-tools/scripts/manifest.yml
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
#745 
This PR is to add data prepper 1.0.0 version for releases
No Need
> Add data prepper 1.0.0 version for releases

- .github/workflows/check-vulnerability-whitesource.yml
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Change the WhiteSource CVEs scan from once a day to run every 2 hours. 
> Update the whitesource scan to run every 2 hours

- .github/workflows/check-vulnerability-whitesource.yml
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Reduce the WhiteSource CVEs scan workflow frequency from once every 2 hours to run once a day.
> Reduce the frequency of WhiteSource scan workflow
